// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/card.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/nu-kotov/GophKeeper/internal/models"
)

// MockCardStorage is a mock of CardStorage interface.
type MockCardStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCardStorageMockRecorder
}

// MockCardStorageMockRecorder is the mock recorder for MockCardStorage.
type MockCardStorageMockRecorder struct {
	mock *MockCardStorage
}

// NewMockCardStorage creates a new mock instance.
func NewMockCardStorage(ctrl *gomock.Controller) *MockCardStorage {
	mock := &MockCardStorage{ctrl: ctrl}
	mock.recorder = &MockCardStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardStorage) EXPECT() *MockCardStorageMockRecorder {
	return m.recorder
}

// DeleteCardData mocks base method.
func (m *MockCardStorage) DeleteCardData(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCardData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCardData indicates an expected call of DeleteCardData.
func (mr *MockCardStorageMockRecorder) DeleteCardData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCardData", reflect.TypeOf((*MockCardStorage)(nil).DeleteCardData), arg0, arg1, arg2)
}

// InsertCardData mocks base method.
func (m *MockCardStorage) InsertCardData(arg0 context.Context, arg1 string, arg2 *models.CardData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCardData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCardData indicates an expected call of InsertCardData.
func (mr *MockCardStorageMockRecorder) InsertCardData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCardData", reflect.TypeOf((*MockCardStorage)(nil).InsertCardData), arg0, arg1, arg2)
}

// SelectCardData mocks base method.
func (m *MockCardStorage) SelectCardData(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCardData", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCardData indicates an expected call of SelectCardData.
func (mr *MockCardStorageMockRecorder) SelectCardData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCardData", reflect.TypeOf((*MockCardStorage)(nil).SelectCardData), arg0, arg1, arg2)
}
