// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/text.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/nu-kotov/GophKeeper/internal/models"
)

// MockTextStorage is a mock of TextStorage interface.
type MockTextStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTextStorageMockRecorder
}

// MockTextStorageMockRecorder is the mock recorder for MockTextStorage.
type MockTextStorageMockRecorder struct {
	mock *MockTextStorage
}

// NewMockTextStorage creates a new mock instance.
func NewMockTextStorage(ctrl *gomock.Controller) *MockTextStorage {
	mock := &MockTextStorage{ctrl: ctrl}
	mock.recorder = &MockTextStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextStorage) EXPECT() *MockTextStorageMockRecorder {
	return m.recorder
}

// DeleteTextData mocks base method.
func (m *MockTextStorage) DeleteTextData(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTextData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTextData indicates an expected call of DeleteTextData.
func (mr *MockTextStorageMockRecorder) DeleteTextData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTextData", reflect.TypeOf((*MockTextStorage)(nil).DeleteTextData), arg0, arg1, arg2)
}

// InsertTextData mocks base method.
func (m *MockTextStorage) InsertTextData(arg0 context.Context, arg1 string, arg2 *models.TextData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTextData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTextData indicates an expected call of InsertTextData.
func (mr *MockTextStorageMockRecorder) InsertTextData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTextData", reflect.TypeOf((*MockTextStorage)(nil).InsertTextData), arg0, arg1, arg2)
}

// SelectTextData mocks base method.
func (m *MockTextStorage) SelectTextData(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectTextData", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectTextData indicates an expected call of SelectTextData.
func (mr *MockTextStorageMockRecorder) SelectTextData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectTextData", reflect.TypeOf((*MockTextStorage)(nil).SelectTextData), arg0, arg1, arg2)
}
