// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/binary.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	minio "github.com/minio/minio-go/v7"
)

// MockBinaryStorage is a mock of BinaryStorage interface.
type MockBinaryStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBinaryStorageMockRecorder
}

// MockBinaryStorageMockRecorder is the mock recorder for MockBinaryStorage.
type MockBinaryStorageMockRecorder struct {
	mock *MockBinaryStorage
}

// NewMockBinaryStorage creates a new mock instance.
func NewMockBinaryStorage(ctrl *gomock.Controller) *MockBinaryStorage {
	mock := &MockBinaryStorage{ctrl: ctrl}
	mock.recorder = &MockBinaryStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinaryStorage) EXPECT() *MockBinaryStorageMockRecorder {
	return m.recorder
}

// DeleteBinaryData mocks base method.
func (m *MockBinaryStorage) DeleteBinaryData(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinaryData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinaryData indicates an expected call of DeleteBinaryData.
func (mr *MockBinaryStorageMockRecorder) DeleteBinaryData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinaryData", reflect.TypeOf((*MockBinaryStorage)(nil).DeleteBinaryData), arg0, arg1, arg2)
}

// InsertBinaryData mocks base method.
func (m *MockBinaryStorage) InsertBinaryData(arg0 context.Context, arg1, arg2 string, arg3 io.ReadCloser) (*minio.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBinaryData", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*minio.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertBinaryData indicates an expected call of InsertBinaryData.
func (mr *MockBinaryStorageMockRecorder) InsertBinaryData(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBinaryData", reflect.TypeOf((*MockBinaryStorage)(nil).InsertBinaryData), arg0, arg1, arg2, arg3)
}

// SelectBinaryData mocks base method.
func (m *MockBinaryStorage) SelectBinaryData(arg0 context.Context, arg1, arg2 string) (*minio.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBinaryData", arg0, arg1, arg2)
	ret0, _ := ret[0].(*minio.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBinaryData indicates an expected call of SelectBinaryData.
func (mr *MockBinaryStorageMockRecorder) SelectBinaryData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBinaryData", reflect.TypeOf((*MockBinaryStorage)(nil).SelectBinaryData), arg0, arg1, arg2)
}
