// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/nu-kotov/GophKeeper/internal/models"
)

// MockUsersStorage is a mock of UsersStorage interface.
type MockUsersStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUsersStorageMockRecorder
}

// MockUsersStorageMockRecorder is the mock recorder for MockUsersStorage.
type MockUsersStorageMockRecorder struct {
	mock *MockUsersStorage
}

// NewMockUsersStorage creates a new mock instance.
func NewMockUsersStorage(ctrl *gomock.Controller) *MockUsersStorage {
	mock := &MockUsersStorage{ctrl: ctrl}
	mock.recorder = &MockUsersStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersStorage) EXPECT() *MockUsersStorageMockRecorder {
	return m.recorder
}

// InsertUserData mocks base method.
func (m *MockUsersStorage) InsertUserData(arg0 context.Context, arg1 *models.UserData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserData indicates an expected call of InsertUserData.
func (mr *MockUsersStorageMockRecorder) InsertUserData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserData", reflect.TypeOf((*MockUsersStorage)(nil).InsertUserData), arg0, arg1)
}

// SelectUserData mocks base method.
func (m *MockUsersStorage) SelectUserData(arg0 context.Context, arg1 *models.UserData) (*models.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserData", arg0, arg1)
	ret0, _ := ret[0].(*models.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserData indicates an expected call of SelectUserData.
func (mr *MockUsersStorageMockRecorder) SelectUserData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserData", reflect.TypeOf((*MockUsersStorage)(nil).SelectUserData), arg0, arg1)
}
