// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/credentials.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/nu-kotov/GophKeeper/internal/models"
)

// MockCredentialsStorage is a mock of CredentialsStorage interface.
type MockCredentialsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsStorageMockRecorder
}

// MockCredentialsStorageMockRecorder is the mock recorder for MockCredentialsStorage.
type MockCredentialsStorageMockRecorder struct {
	mock *MockCredentialsStorage
}

// NewMockCredentialsStorage creates a new mock instance.
func NewMockCredentialsStorage(ctrl *gomock.Controller) *MockCredentialsStorage {
	mock := &MockCredentialsStorage{ctrl: ctrl}
	mock.recorder = &MockCredentialsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsStorage) EXPECT() *MockCredentialsStorageMockRecorder {
	return m.recorder
}

// DeleteCredentialsData mocks base method.
func (m *MockCredentialsStorage) DeleteCredentialsData(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentialsData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredentialsData indicates an expected call of DeleteCredentialsData.
func (mr *MockCredentialsStorageMockRecorder) DeleteCredentialsData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentialsData", reflect.TypeOf((*MockCredentialsStorage)(nil).DeleteCredentialsData), arg0, arg1, arg2)
}

// InsertCredentialsData mocks base method.
func (m *MockCredentialsStorage) InsertCredentialsData(arg0 context.Context, arg1 string, arg2 *models.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCredentialsData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCredentialsData indicates an expected call of InsertCredentialsData.
func (mr *MockCredentialsStorageMockRecorder) InsertCredentialsData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCredentialsData", reflect.TypeOf((*MockCredentialsStorage)(nil).InsertCredentialsData), arg0, arg1, arg2)
}

// SelectCredentialsData mocks base method.
func (m *MockCredentialsStorage) SelectCredentialsData(arg0 context.Context, arg1, arg2 string) (*models.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCredentialsData", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCredentialsData indicates an expected call of SelectCredentialsData.
func (mr *MockCredentialsStorageMockRecorder) SelectCredentialsData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCredentialsData", reflect.TypeOf((*MockCredentialsStorage)(nil).SelectCredentialsData), arg0, arg1, arg2)
}
